using UnityEngine;
using UnityEngine.EventSystems;
public class CellScript : MonoBehaviour, IPointerClickHandler
{
    public GameObject BuildselectionPanel;
    public bool busy현ll;
    private GameObject UIelem;
    void Awake()
    {
        UIelem =  GameObject.Find("Main Camera");
        busy현ll = true;
        BuildselectionPanel = GameObject.Find("BuildSelectionPanel");
    }
    public void OnPointerClick(PointerEventData eventData)
    {
        if (busy현ll == true)
        {
            BuildselectionPanel.SetActive(true);
            BuildselectionPanel.GetComponent<BuildSelectionPanelScript>().buildPos = transform.position;
            BuildselectionPanel.GetComponent<BuildSelectionPanelScript>().Parent = gameObject;
            UIelem.GetComponent<UIScript>().Cell = gameObject;
        }
    }
    private void OnTriggerEnter(Collider other)
    {
        busy현ll = false;
    }
    private void OnTriggerExit(Collider other)
    {
        busy현ll = true;
    }
}
